version: "3.8"

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  app:
    image: your_dockerhub_username/kaiburr-task-api:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/taskdb
    depends_on:
      - mongo
