name: CI-CD Pipeline for Kaiburr Task API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # GitHub Actions MongoDB service hostname
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/taskdb

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - run: mvn -B clean package -DskipTests

      - run: docker build -t kaiburr-task-api:latest .

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          docker tag kaiburr-task-api:latest ${{ secrets.DOCKERHUB_USERNAME }}/kaiburr-task-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/kaiburr-task-api:latest
